#!/bin/bash
#
me=$(basename $0)
origin=$(pwd)
dir="$1"
offset=40

# Case insensitive globbing
shopt -s nocaseglob

if [  -z $dir ]; then
  echo "Usage: $me <directory>"
  exit 1
fi
if [ ! -d $dir ]; then
  echo "directory $dir does not exist"
  exit 1
fi

(
  echo "Working in $dir"
  cd $dir
  shopt -s nocaseglob

  mkdir tmp

  fit=$(ls *.FIT 2>/dev/null | head -1)
  if [ -z "$fit" ]; then
    echo "No fit file found in $dir"
    exit 1
  fi
  echo "Using fit file $fit"

  # Find all files named *.mp4
  for file in *.MP4; do
    # skip if filename contains "overlay"
    if [[ $file == *overlay* ]]; then
      echo "Skipping file $file"
      continue
    fi
    echo "Processing file $file"
    date=$(ffprobe $file 2>&1 | grep creation_time | head -1 | awk -F": " '{print $2}')
    #timestamp=$(date -ju -f "%Y-%m-%dT%H:%M:%S" "$date" "+%s")
    #timestamp=$((timestamp+offset))
    #date=$(date -r "$timestamp" +"%Y-%m-%dT%H:%M:%S.000000Z")

    echo "Date of file is $date"
    touch -d $date -m $file

    echo "Transcoding file $file to tmp/$file"
#    $origin/venv/gopro-overlay/bin/gopro-dashboard.py \
#      --font Arial \
#      --units-speed kph \
#      --units-altitude meter \
#      --units-temperature degC \
#      --fit $fit \
#      --use-fit-only \
#      --video-time-start file-modified \
#      --profile overlay-mac \
#      $file tmp/$file
  done

  # create a tmp/file.txt with the list of files to be processed
  > tmp/file.txt
  for file in tmp/*.MP4; do
    basefile=$(basename $file)
    echo "file '$basefile'" >> tmp/file.txt
  done

  # Merge all files using ffmpeg
  echo "Merging file to overlay.mp4"
  ffmpeg -f concat -safe 0 -i tmp/file.txt -c copy overlay.mp4
)

